# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Security.proto
# Protobuf Python Version: 4.25.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0eSecurity.proto\x12\rhadoop.common\"Q\n\nTokenProto\x12\x12\n\nidentifier\x18\x01 \x02(\x0c\x12\x10\n\x08password\x18\x02 \x02(\x0c\x12\x0c\n\x04kind\x18\x03 \x02(\t\x12\x0f\n\x07service\x18\x04 \x02(\t\"1\n\x1eGetDelegationTokenRequestProto\x12\x0f\n\x07renewer\x18\x01 \x02(\t\"K\n\x1fGetDelegationTokenResponseProto\x12(\n\x05token\x18\x01 \x01(\x0b\x32\x19.hadoop.common.TokenProto\"L\n RenewDelegationTokenRequestProto\x12(\n\x05token\x18\x01 \x02(\x0b\x32\x19.hadoop.common.TokenProto\":\n!RenewDelegationTokenResponseProto\x12\x15\n\rnewExpiryTime\x18\x01 \x02(\x04\"M\n!CancelDelegationTokenRequestProto\x12(\n\x05token\x18\x01 \x02(\x0b\x32\x19.hadoop.common.TokenProto\"$\n\"CancelDelegationTokenResponseProtoB8\n org.apache.hadoop.security.protoB\x0eSecurityProtos\x88\x01\x01\xa0\x01\x01')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'Security_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n org.apache.hadoop.security.protoB\016SecurityProtos\210\001\001\240\001\001'
  _globals['_TOKENPROTO']._serialized_start=33
  _globals['_TOKENPROTO']._serialized_end=114
  _globals['_GETDELEGATIONTOKENREQUESTPROTO']._serialized_start=116
  _globals['_GETDELEGATIONTOKENREQUESTPROTO']._serialized_end=165
  _globals['_GETDELEGATIONTOKENRESPONSEPROTO']._serialized_start=167
  _globals['_GETDELEGATIONTOKENRESPONSEPROTO']._serialized_end=242
  _globals['_RENEWDELEGATIONTOKENREQUESTPROTO']._serialized_start=244
  _globals['_RENEWDELEGATIONTOKENREQUESTPROTO']._serialized_end=320
  _globals['_RENEWDELEGATIONTOKENRESPONSEPROTO']._serialized_start=322
  _globals['_RENEWDELEGATIONTOKENRESPONSEPROTO']._serialized_end=380
  _globals['_CANCELDELEGATIONTOKENREQUESTPROTO']._serialized_start=382
  _globals['_CANCELDELEGATIONTOKENREQUESTPROTO']._serialized_end=459
  _globals['_CANCELDELEGATIONTOKENRESPONSEPROTO']._serialized_start=461
  _globals['_CANCELDELEGATIONTOKENRESPONSEPROTO']._serialized_end=497
# @@protoc_insertion_point(module_scope)
